vJSCC_DB['ClassList']['WikiDownloader'] = {
    "JSCC_type": "CLASS",
    "JSCC_init_date": "18.10.2017",
    "JSCC_mod_date": "2017/11/19 18:11:10",
    "tClassname": "WikiDownloader",
    "tSuperClassname": "",
    "sClassType": "Default",
    "tAuthor": "Engelbert Niehaus",
    "tEMail": "niehaus@uni-landau.de",
    "tAttributes": "",
    "tMethods": "init(pURL:String)\ndownload()\nconvertLink():String\nreplaceWikiMath()\nsetSource(pText:String)\ngetSource():String\nconvertLink2Web()\ncreateMediaArray()\ndownloadZIP()\nconvertMedia2Local()",
    "sAttribList": "",
    "tAttribName": "",
    "tAttribType": "",
    "tAttribComment": "",
    "tAttribDefault": "",
    "sAttribTypeList": "",
    "tMethodHeader": "downloadZIP()",
    "tMethodName": "",
    "tMethodComment": "what does downloadZIP do?",
    "sMethodList": "downloadZIP",
    "tMethodCode": "",
    "tLoopObject": "",
    "tLoopMethod": "",
    "AttribType": {},
    "AttribAccess": {},
    "AttribDefault": {},
    "AttribComment": {},
    "MethodParameter": {
        "init": "pURL:String",
        "download": "",
        "convertLink": "",
        "replaceWikiMath": "",
        "setSource": "pText:String",
        "getSource": "",
        "convertLink2Web": "",
        "createMediaArray": "",
        "downloadZIP": "",
        "convertMedia2Local": ""
    },
    "MethodReturn": {
        "init": "",
        "download": "",
        "convertLink": "String",
        "replaceWikiMath": "",
        "setSource": "",
        "getSource": "String",
        "convertLink2Web": "",
        "createMediaArray": "",
        "downloadZIP": "",
        "convertMedia2Local": ""
    },
    "MethodCode": {
        "init": "",
        "download": "",
        "convertLink": "",
        "replaceWikiMath": "",
        "setSource": "",
        "getSource": "",
        "convertLink2Web": "",
        "createMediaArray": "",
        "downloadZIP": "",
        "convertMedia2Local": ""
    },
    "MethodComment": {
        "init": "Comment for init",
        "download": "Comment for download",
        "convertLink": "Comment for convertLink",
        "replaceWikiMath": "Comment for replaceWikiMath",
        "setSource": "Comment for setSource",
        "getSource": "Comment for getSource",
        "convertLink2Web": "Comment for convertLink2Web",
        "createMediaArray": "Comment for createMediaArray",
        "downloadZIP": "what does downloadZIP do?",
        "convertMedia2Local": "Comment for convertMedia2Local"
    },
    "MethodAccess": {
        "init": "public",
        "download": "public",
        "convertLink": "public",
        "replaceWikiMath": "public",
        "setSource": "public",
        "getSource": "public",
        "convertLink2Web": "public",
        "createMediaArray": "public",
        "downloadZIP": "public",
        "convertMedia2Local": "public"
    },
    "sClassList": "WikiDownloader",
    "tMethodAccess": "public",
    "JSCC_version": "1"
}